spring:
    application:
        name: config-server
    #    cloud:
    #        config:
    #            server:
    #                git:
    #                    uri: https://github.com/Malcolm-G/app-config
    #    # Username and password in case repo is private. Add env variables so as to not commit credentials
    #    #                    username: ${GIT_USER}
    #    #                    password: ${GIT_TOKEN} uSE
    profiles:
        active: native ## Specify profile because by default it tries to use git
#    datasource:
#        url: jdbc:mysql://localhost:3306/configdb
#        username: ${MYSQL_USER}
#        password: ${MYSQL_PASS}
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    cloud:
#        config:
#            server:
#                jdbc:
#                    sql: "SELECT prop_key, prop_value FROM properties WHERE application = ? AND profile = ? AND label = ?"
#                    default-label: main
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config

server:
    port: 8888

## Note: Spring knows to decrypt db value when it starts with {cipher}

#encrypt:
#    key: ${AES_KEY} ## AES key is used. This should be a hexadecimal that's more appropriate.
encrypt:
    key-store:
        location: config-server.jks
        password: mypass
        alias: config-server-key
